# Generated by Django 4.0 on 2024-09-09 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_name", models.CharField(max_length=256)),
            ],
            options={
                "db_table": "clients",
            },
        ),
        migrations.CreateModel(
            name="ClientInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("info", models.CharField(max_length=256)),
            ],
            options={
                "db_table": "clients_info",
            },
        ),
        migrations.CreateModel(
            name="Endpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("endpoint_name", models.CharField(max_length=256)),
            ],
            options={
                "db_table": "endpoints",
            },
        ),
        migrations.CreateModel(
            name="EndpointStates",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state_name", models.CharField(max_length=256)),
                ("state_reason", models.CharField(max_length=256)),
                ("state_start", models.CharField(max_length=256)),
                ("state_end", models.CharField(max_length=256)),
                ("state_id", models.CharField(max_length=256)),
                ("group_id", models.CharField(max_length=256)),
                ("reason_group", models.CharField(max_length=256)),
                ("info", models.JSONField(default={})),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="fast_api.client",
                    ),
                ),
                (
                    "endpoint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="fast_api.endpoint",
                    ),
                ),
            ],
            options={
                "db_table": "endpoints_states",
            },
        ),
        migrations.AddField(
            model_name="client",
            name="client_info",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="fast_api.clientinfo",
            ),
        ),
    ]
